version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    volumes:
    - ./initialize_data.sh:/srachat/backend/initialize_data.sh
    environment:
      DEBUG: 1
      POSTGRES_HOST: db
    command: >
      sh -c " ls -la && chmod +x initialize_data.sh && \
              python3 manage.py migrate && \
              daphne root.asgi:application --port 8000 --bind 0.0.0.0 -v2"
    ports:
      - 8000:8000
    depends_on:
      - db
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
