version: '3'

services:
  db:
    image: postgres
    environment:
      # those are used to configure the db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    environment:
      # those are used to connect to a db
      POSTGRES_HOST: db
    build: .
    command: bash -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/root
    ports:
      - "8000:8000"
    depends_on:
      - db