# Generated by Django 3.0.3 on 2020-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_users', to='chat.Room'),
        ),
    ]
