# Generated by Django 3.0.3 on 2020-04-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200406_0007'),
        ('chat', '0005_chatuser_image'),
    ]

    operations = [
    ]
