# Generated by Django 3.1.1 on 2020-11-01 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_initial_tags(apps, schema_editor):
    """
    Initializing some initial tags, which would be the same in dev and prod envs.
    Those initial tags are:
    - Others
    - Animals
    - Anime
    - Consoles
    - Drugs
    - Politics
    """
    Tag = apps.get_model('srachat', 'Tag')
    for tag_name in ["Others", "Animals", "Anime", "Consoles", "Drugs", "Politics"]:
        Tag.objects.create(name=tag_name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('first_team_name', models.CharField(max_length=30)),
                ('second_team_name', models.CharField(max_length=30)),
                ('first_team_votes', models.PositiveSmallIntegerField(default=0)),
                ('second_team_votes', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('GE', 'German'), ('RU', 'Russian')], default='RU', max_length=2)),
                ('max_participants_in_team', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(50)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('admins', models.ManyToManyField(default=[], related_name='administrated_rooms', to='srachat.ChatUser')),
                ('banned_users', models.ManyToManyField(blank=True, related_name='forbidden_rooms', to='srachat.ChatUser')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_room', to='srachat.chatuser')),
                ('tags', models.ManyToManyField(related_name='rooms', to='srachat.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team')])),
                ('chatuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.chatuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.room')),
            ],
            options={
                'unique_together': {('chatuser', 'room')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team_number', models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to='srachat.chatuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='srachat.room')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='chatuser',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_users', through='srachat.Participation', to='srachat.Room'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team'), (0, 'Remove vote')])),
                ('date_voted', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.room')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.chatuser')),
            ],
            options={
                'unique_together': {('voter', 'room')},
            },
        ),
        migrations.RunPython(create_initial_tags)
    ]
