# Generated by Django 3.1.1 on 2020-09-23 22:35

from django.db import migrations


def populate_db_all_models(apps, schema_editor):
    User = apps.get_model("auth", "User")
    first_user = User.objects.create(username="first_user")
    second_user = User.objects.create(username="second_user")

    ChatUser = apps.get_model("srachat", "ChatUser")
    first_chat_user = ChatUser.objects.create(user=first_user)
    second_chat_user = ChatUser.objects.create(user=second_user)

    Room = apps.get_model("srachat", "Room")
    first_room = Room.objects.create(creator=first_chat_user, title="first_room")
    second_room = Room.objects.create(creator=second_chat_user, title="second_room")
    first_room.chat_users.add(first_chat_user)
    first_room.chat_users.add(second_chat_user)
    second_room.chat_users.add(first_chat_user)
    second_room.chat_users.add(second_chat_user)

    Comment = apps.get_model("srachat", "Comment")
    Comment.objects.create(body="first_comment", creator=first_chat_user, room=first_room)
    Comment.objects.create(body="second_comment", creator=second_chat_user, room=first_room)
    Comment.objects.create(body="third_comment", creator=first_chat_user, room=second_room)
    Comment.objects.create(body="fourth_comment", creator=second_chat_user, room=second_room)


class Migration(migrations.Migration):

    dependencies = [
        ('srachat', '0007_merge_20200406_0200'),
    ]

    operations = [
        migrations.RunPython(populate_db_all_models)
    ]
