# Generated by Django 3.0.3 on 2020-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srachat', '0007_merge_20200406_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(related_name='room_tags', to='srachat.Tag'),
        ),
    ]
