# Generated by Django 3.1.1 on 2020-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srachat', '0008_auto_20201012_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(default=[], related_name='administrated_rooms', to='srachat.ChatUser'),
        ),
    ]
