# Generated by Django 3.1.1 on 2020-10-28 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srachat', '0009_room_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='forbidden_rooms', to='srachat.ChatUser'),
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='first_team_name',
            field=models.CharField(default='f', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='first_team_votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GE', 'German'), ('RU', 'Russian')], default='RU', max_length=2),
        ),
        migrations.AddField(
            model_name='room',
            name='max_participants_in_team',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='room',
            name='second_team_name',
            field=models.CharField(default='s', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='second_team_votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team')])),
                ('chatuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.chatuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.room')),
            ],
            options={
                'unique_together': {('chatuser', 'room')},
            },
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='rooms',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_users', through='srachat.Participation', to='srachat.Room'),
        ),
        migrations.CreateModel(
            name='RoomVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField(choices=[(1, 'First Team'), (2, 'Second Team'), (0, 'Remove vote')])),
                ('date_voted', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.room')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srachat.chatuser')),
            ],
            options={
                'unique_together': {('voter', 'room')},
            },
        ),
    ]
