name: Deploy

on:
  push:
    tags:
      - version-[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: srachat
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
          healthcheck: "https://srachat.herokuapp.com/health"
          delay: 60
          rollbackonhealthcheckfailed: true
          usedocker: true